export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_DATA_STARTED = 'FETCH_DATA_STARTED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const AUTHENTICATE_STARTED = 'AUTHENTICATE_STARTED';
export const ADD_USERNAME = 'ADD_USERNAME';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const INIT_STATE = 'INIT_STATE';

export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const COCKTAIL_BY_ID_STARTED = 'COCKTAIL_BY_ID_STARTED';
export const COCKTAIL_BY_ID_SUCCESS = 'COCKTAIL_BY_ID_SUCCESS';
export const COCKTAIL_BY_ID_FAILURE = 'COCKTAIL_BY_ID_FAILURE';
